export const ALL_FONTS: string[] = [
    "Arial",
    "Verdana",
    "Times New Roman",
    "Courier New",
    "Georgia",
    "Comic Sans MS",
    "Impact",
    "Tahoma",
    "Trebuchet MS",
    "Lucida Console",
    "Garamond",
    "Palatino Linotype",
    "Book Antiqua",
    "Monaco",
    "Futura",
    "Baskerville",
    "Century Gothic",
    "Franklin Gothic Medium",
    "Gill Sans",
    "Geneva",
    "Optima",
    "Brush Script MT",
    "Copperplate",
    "Segoe UI",
    "Calibri",
    "Cambria",
    "Didot",
    "Rockwell",
    "Arial Black",
    "Comic Neue",
    "Lora",
    "Merriweather",
    "Montserrat",
    "Noto Sans",
    "Open Sans",
    "Oswald",
    "Poppins",
    "Raleway",
    "Roboto",
    "Rubik",
    "Source Sans Pro",
    "Space Grotesk",
    "Titillium Web",
    "Ubuntu",
    "Zilla Slab",
];
